services:
  # --- Base de données ---
  db:
    image: postgres:17-alpine
    container_name: tenuki-postgres
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - ../database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - tenuki-pgdata:/var/lib/postgresql/data
    healthcheck: # Pour que le backend attende vraiment que la DB soit prête
      test: ["CMD-SHELL", "pg_isready -U go_user -d go_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Backend ---
  backend:
    build: ../backend
    container_name: tenuki-backend
    command: python main.py
    volumes:
      - ../backend:/app
      - ./storage:/app/storage # Montage du volume pour les fichiers uploadés
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://go_user:secret@db:5432/go_db
      - ANALYSIS_SERVICE_URL=http://analysis:5000
      - ANALYSIS_CALLBACK_URL=http://backend:8000/video/video_id/analysis-complete
      - PHOTO_SERVICE_URL=http://photo:5001
      - MEDIAMTX_RTSP_URL=rtsp://mediamtx:8554
      - WS_STREAMING_URL=ws://backend:8000/ws/match
    depends_on:
      db:
        condition: service_healthy

  # --- Frontend ---
  frontend:
    build: ../frontend
    container_name: tenuki-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next # Préserve le cache de build Next.js (IMPORTANT pour la vitesse)
    environment:
      - NEXT_PUBLIC_DOCKER_STORAGE_URL=http://backend:8000/storage/
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  # --- Module d'analyse ---
  analysis:
    build: ../modules/analysis
    container_name: tenuki-analysis
    command: python main.py
    volumes:
      - ../modules/analysis:/app
      - ./storage:/app/storage # Montage du même volume pour accéder aux fichiers uploadés
    ports:
      - "5000:5000"
    environment:
      - CUDA_VISIBLE_DEVICES=-1 # Désactive l'utilisation du GPU (à ajuster selon le déploiement)
      - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp|fflags;discardcorrupt|flags;low_delay

  # --- Module photo/completion ---
  photo:
    build: ../modules/photo
    container_name: tenuki-photo
    command: uvicorn api:app --host 0.0.0.0 --port 5001
    volumes:
      - ../modules/photo:/app
      - ./storage:/app/storage
    ports:
      - "5001:5001"

  # --- Module de Streaming (MediaMTX) ---
  mediamtx:
    image: bluenviron/mediamtx:1.15.4
    container_name: tenuki-mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP (Entrée)
      - "8080:8080"   # HLS (Sortie Web)
      - "9997:9997"   # API (Gestion)
      - "8554:8554"   # RTSP (Sortie pour l'analyseur)
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
      - ./storage:/tenuki_storage

volumes:
  tenuki-pgdata: