services:
  # --- Base de données ---
  db:
    image: postgres:16
    container_name: tenuki-postgres
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - ../database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - tenuki-pgdata:/var/lib/postgresql/data

  # --- Backend ---
  backend:
    build: ../backend
    container_name: tenuki-backend
    command: python main.py
    volumes:
      - ../backend:/app
      - uploads_data:/app/uploads # Montage du volume pour les fichiers uploadés
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://go_user:secret@db:5432/go_db
      - ANALYSE_SERVICE_URL=http://analyse:5000 # URL interne Docker
      - MEDIAMTX_API_URL=http://mediamtx:9997
      - CLUB_PASSWORD
    depends_on:
      - db

  # --- Frontend ---
  frontend:
    build: ../frontend
    container_name: tenuki-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next              # Préserve le cache de build Next.js (IMPORTANT pour la vitesse)
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_PASSWORD
      # --- AJOUTS POUR LE HOT RELOAD ---
      - WATCHPACK_POLLING=true      # Force Webpack à utiliser le polling
      - CHOKIDAR_USEPOLLING=true    # Force Chokidar (watcher de fichiers) à utiliser le polling

  # --- Module analyse ---
  analyse:
    build: ../modules/analyse
    container_name: tenuki-analyse
    command: python api.py
    volumes:
      - ../modules/analyse:/app
      - uploads_data:/app/uploads # Montage du même volume pour accéder aux fichiers uploadés
    ports:
      - "5000:5000"
    environment:
      - RTSP_STREAM_URL=rtsp://mediamtx:8554
      - TF_ENABLE_ONEDNN_OPTS=0

  # --- Module de Streaming (MediaMTX) ---
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: tenuki-mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP (Entrée)
      - "8080:8080"   # HLS (Sortie Web)
      - "8889:8889"   # WebRTC (Sortie Web faible latence)
      - "9997:9997"   # API (Gestion)
      - "8554:8554"   # RTSP (Entrée/Sortie pour l'analyseur)
    volumes:
      - ../modules/streaming/mediamtx.yml:/mediamtx.yml:ro
      # Enregistrements : Stockés dans modules/diffusion/recordings
      - ../modules/streaming/recordings:/project_recordings

volumes:
  tenuki-pgdata:
  uploads_data: # Volume nommé pour partager les fichiers