logLevel: info

api: yes
apiAddress: :9997

rtmp: yes
rtmpAddress: :1935

hls: yes
hlsAddress: :8080

rtsp: yes
rtspAddress: :8554

rtspTransports: [tcp]

paths:
  all:
    source: publisher
    record: yes
    # %Y%m%d_%H%M%S ensures a unique file name per session.
    recordPath: /tenuki_storage/videos/%path/%Y%m%d_%H%M%S
    recordFormat: fmp4
